/**
 * Mock Data for Tasks Page
 * Includes structured SOPs with checklist steps
 */

import type { Task } from '@/features/tasks/types/task.types';
import type { StandardOperatingProcedure, SopProgress } from '@/features/tasks/types/sop.types';
import type { ApplicationTaskDetails } from '@/features/tasks/types/application.types';

// Mock Application Task Details
const MOCK_APPLICATION_DETAILS: Record<string, ApplicationTaskDetails> = {
  '6': {
    applicationType: 'fertigation',
    recipeId: 'recipe-bloom-wk3',
    recipeVersionId: 'recipe-bloom-wk3-v2',
    recipe: {
      id: 'recipe-bloom-wk3',
      name: 'Bloom Week 3 Formula',
      version: 2,
      description: 'Mid-flower formula with increased P/K for bud development',
      applicationType: 'fertigation',
      targetEcMscm: 2.2,
      targetEcTolerance: 0.1,
      targetPh: 5.9,
      targetPhTolerance: 0.1,
      applicationMethod: 'drip',
      applicationRate: '100ml/plant',
      components: [
        {
          id: 'comp1',
          recipeId: 'recipe-bloom-wk3',
          order: 1,
          productId: 'prod-base-a',
          productSku: 'NUT-BASE-A',
          productName: 'Bloom Base A',
          amountPerUnit: 3.5,
          amountUom: 'ml',
          perUnitType: 'liter',
          unitCost: 0.15,
        },
        {
          id: 'comp2',
          recipeId: 'recipe-bloom-wk3',
          order: 2,
          productId: 'prod-base-b',
          productSku: 'NUT-BASE-B',
          productName: 'Bloom Base B',
          amountPerUnit: 3.5,
          amountUom: 'ml',
          perUnitType: 'liter',
          unitCost: 0.15,
        },
        {
          id: 'comp3',
          recipeId: 'recipe-bloom-wk3',
          order: 3,
          productId: 'prod-pk-boost',
          productSku: 'NUT-PK-13-14',
          productName: 'PK 13/14 Booster',
          amountPerUnit: 1.0,
          amountUom: 'ml',
          perUnitType: 'liter',
          unitCost: 0.25,
        },
      ],
      createdAt: new Date().toISOString(),
      createdBy: 'u2',
      isActive: true,
    },
    target: {
      roomId: 'f1',
      roomName: 'Flower Room 1',
      targetType: 'room',
      plantCount: 48,
      estimatedAreaSqFt: 400,
      estimatedVolumeLiters: 200,
    },
    plannedMaterials: [
      {
        id: 'pm1',
        applicationTaskId: '6',
        recipeComponentId: 'comp1',
        productId: 'prod-base-a',
        productName: 'Bloom Base A',
        productSku: 'NUT-BASE-A',
        plannedQuantity: 700,
        uom: 'ml',
        allocatedLotId: 'lot-base-a-001',
        allocatedLotNumber: 'BA-2024-001',
        allocatedQuantity: 700,
        estimatedUnitCost: 0.00015,
        estimatedTotalCost: 0.105,
      },
      {
        id: 'pm2',
        applicationTaskId: '6',
        recipeComponentId: 'comp2',
        productId: 'prod-base-b',
        productName: 'Bloom Base B',
        productSku: 'NUT-BASE-B',
        plannedQuantity: 700,
        uom: 'ml',
        allocatedLotId: 'lot-base-b-001',
        allocatedLotNumber: 'BB-2024-001',
        allocatedQuantity: 700,
        estimatedUnitCost: 0.00015,
        estimatedTotalCost: 0.105,
      },
      {
        id: 'pm3',
        applicationTaskId: '6',
        recipeComponentId: 'comp3',
        productId: 'prod-pk-boost',
        productName: 'PK 13/14 Booster',
        productSku: 'NUT-PK-13-14',
        plannedQuantity: 200,
        uom: 'ml',
        estimatedUnitCost: 0.00025,
        estimatedTotalCost: 0.05,
      },
    ],
    materialConsumptions: [],
  },
  '7': {
    applicationType: 'ipm',
    recipeId: 'recipe-regalia',
    recipeVersionId: 'recipe-regalia-v1',
    recipe: {
      id: 'recipe-regalia',
      name: 'Regalia Preventative Spray',
      version: 1,
      description: 'Preventative fungicide spray for PM and mildew prevention',
      applicationType: 'ipm',
      applicationMethod: 'foliar',
      dilutionRatio: '4ml/L',
      applicationRate: '1L/10sqft',
      reEntryIntervalHours: 4,
      preHarvestIntervalDays: 0,
      ppeRequired: ['gloves', 'eye_protection', 'respirator'],
      components: [
        {
          id: 'comp-reg1',
          recipeId: 'recipe-regalia',
          order: 1,
          productId: 'prod-regalia',
          productSku: 'IPM-REG-1L',
          productName: 'Regalia Biofungicide',
          amountPerUnit: 4,
          amountUom: 'ml',
          perUnitType: 'liter',
          unitCost: 0.85,
        },
      ],
      createdAt: new Date().toISOString(),
      createdBy: 'u1',
      isActive: true,
    },
    target: {
      roomId: 'r2',
      roomName: 'Veg Room 2',
      targetType: 'zones',
      zoneIds: ['z2a'],
      zoneNames: ['Zone A'],
      plantCount: 24,
      estimatedAreaSqFt: 100,
      estimatedVolumeLiters: 10,
    },
    plannedMaterials: [
      {
        id: 'pm-ipm1',
        applicationTaskId: '7',
        recipeComponentId: 'comp-reg1',
        productId: 'prod-regalia',
        productName: 'Regalia Biofungicide',
        productSku: 'IPM-REG-1L',
        plannedQuantity: 40,
        uom: 'ml',
        estimatedUnitCost: 0.00085,
        estimatedTotalCost: 0.034,
      },
    ],
    materialConsumptions: [],
    ppeUsed: ['gloves', 'eye_protection'],
  },
};

export const MOCK_TASKS: Task[] = [
  {
    id: '1',
    title: 'Inspect Mother Room A for PM',
    description: 'Weekly inspection for powdery mildew and other pest issues. Check all mother plants for signs of infection, paying special attention to undersides of leaves and new growth areas.',
    location: 'Room A (Mothers)',
    roomId: 'r1',
    dueAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    priority: 'critical',
    status: 'ready',
    slaStatus: 'breached',
    assignee: { id: 'u1', firstName: 'Brandon', lastName: 'Burnette' },
    category: 'general',
  },
  {
    id: '2',
    title: 'Transplant Batch B-203',
    description: 'Move seedlings from clone room to veg room. Ensure root balls are properly developed before transplanting.',
    location: 'Veg Room 2',
    roomId: 'r2',
    batchId: 'b203',
    dueAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    startedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    priority: 'high',
    status: 'in_progress',
    slaStatus: 'warning',
    assignee: { id: 'u1', firstName: 'Brandon', lastName: 'Burnette' },
    phase: 'veg',
    category: 'general',
  },
  {
    id: '3',
    title: 'Calibrate pH Sensors',
    description: 'Weekly calibration of all pH sensors in irrigation zone 1. Use pH 4.0 and 7.0 calibration solutions.',
    location: 'Irrigation Zone 1',
    dueAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    priority: 'normal',
    status: 'ready',
    slaStatus: 'ok',
    assignee: { id: 'u1', firstName: 'Brandon', lastName: 'Burnette' },
    category: 'general',
  },
  {
    id: '4',
    title: 'Week 3 Defoliation - F1',
    description: 'Perform standard week 3 defoliation on all plants in Flower 1. Remove large fan leaves blocking bud sites.',
    location: 'Flower Room 1',
    roomId: 'f1',
    dueAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'high',
    status: 'blocked',
    slaStatus: 'ok',
    assignee: { id: 'u1', firstName: 'Brandon', lastName: 'Burnette' },
    phase: 'flower',
    category: 'general',
  },
  {
    id: '5',
    title: 'Check Trichomes - Harvest Ready Assessment',
    description: 'Use microscope to assess trichome development. Document percentage of clear, cloudy, and amber trichomes.',
    location: 'Flower Room 2',
    dueAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'normal',
    status: 'ready',
    slaStatus: 'ok',
    phase: 'flower',
    category: 'general',
  },
  // APPLICATION TASK EXAMPLE - Fertigation
  {
    id: '6',
    title: 'Weekly Fertigation - Flower Room 1',
    description: 'Apply Bloom Week 3 formula to all plants in Flower Room 1. Target EC 2.2 mS/cm, pH 5.9.',
    location: 'Flower Room 1',
    roomId: 'f1',
    dueAt: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    priority: 'high',
    status: 'ready',
    slaStatus: 'ok',
    assignee: { 
      id: 'u2', 
      firstName: 'Sarah', 
      lastName: 'Chen',
      permissions: ['applications:fertigation', 'applications:flush']
    },
    phase: 'flower',
    category: 'application',
    applicationType: 'fertigation',
    requiredPermission: 'applications:fertigation',
    applicationDetails: MOCK_APPLICATION_DETAILS['6'],
  },
  // APPLICATION TASK EXAMPLE - IPM
  {
    id: '7',
    title: 'IPM Spray - Veg Room 2 (Zone A)',
    description: 'Apply preventative fungicide spray to Zone A in Veg Room 2. Use Regalia formula at 4ml/L.',
    location: 'Veg Room 2 - Zone A',
    roomId: 'r2',
    zoneId: 'z2a',
    dueAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'normal',
    status: 'ready',
    slaStatus: 'ok',
    assignee: { 
      id: 'u3', 
      firstName: 'Marcus', 
      lastName: 'Johnson',
      permissions: ['applications:ipm', 'applications:beneficial']
    },
    phase: 'veg',
    category: 'application',
    applicationType: 'ipm',
    requiredPermission: 'applications:ipm',
    applicationDetails: MOCK_APPLICATION_DETAILS['7'],
  },
];

// Structured SOPs with interactive checklist steps
export const MOCK_SOPS: Record<string, StandardOperatingProcedure[]> = {
  '1': [
    {
      id: 'sop1',
      orgId: 'org1',
      title: 'IPM Inspection Protocol',
      description: 'Standard procedure for identifying and documenting pest and disease issues.',
      category: 'IPM',
      version: 2,
      isActive: true,
      createdByUserId: 'u2',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      estimatedTotalMinutes: 30,
      requiredEquipment: [
        'Magnifying glass or loupe (10x-30x)',
        'Sticky traps',
        'Camera/phone for photos',
        'IPM log sheet',
        'Nitrile gloves',
      ],
      safetyNotes: [
        'Wear gloves when handling plants',
        'Do not touch face after inspections',
        'Sanitize hands between rooms',
      ],
      steps: [
        {
          id: 'step1',
          order: 1,
          title: 'Prepare for Inspection',
          description: 'Gather all required equipment and ensure you have access to the IPM log.',
          estimatedMinutes: 3,
          subSteps: [
            { id: 'sub1-1', order: 1, text: 'Put on clean nitrile gloves' },
            { id: 'sub1-2', order: 2, text: 'Gather magnifying glass, camera, and log sheet' },
            { id: 'sub1-3', order: 3, text: 'Check sticky traps and note any catches' },
          ],
        },
        {
          id: 'step2',
          order: 2,
          title: 'Visual Inspection - Perimeter',
          description: 'Start inspection at the room perimeter, moving systematically inward.',
          imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
          imageCaption: 'Begin at the perimeter and work inward in a grid pattern',
          estimatedMinutes: 10,
          tipText: 'Pay extra attention to plants near doors, vents, and floor drains.',
          subSteps: [
            { id: 'sub2-1', order: 1, text: 'Inspect plants along all walls and corners' },
            { id: 'sub2-2', order: 2, text: 'Check under tables and benches for debris' },
            { id: 'sub2-3', order: 3, text: 'Examine any plants showing visible stress' },
          ],
        },
        {
          id: 'step3',
          order: 3,
          title: 'Leaf Inspection',
          description: 'Examine both top and underside of leaves for pests or disease.',
          imageUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800',
          imageCaption: 'Check undersides of leaves - where many pests hide',
          warningText: 'Powdery mildew spreads rapidly. If found, isolate immediately.',
          estimatedMinutes: 10,
          subSteps: [
            { id: 'sub3-1', order: 1, text: 'Flip leaves to check undersides (where pests hide)' },
            { id: 'sub3-2', order: 2, text: 'Look for: white powder (PM), yellow spots, webbing (mites)' },
            { id: 'sub3-3', order: 3, text: 'Check new growth tips - pest favorites' },
            { id: 'sub3-4', order: 4, text: 'Document any findings with photos' },
          ],
        },
        {
          id: 'step4',
          order: 4,
          title: 'Stem and Soil Inspection',
          description: 'Check stems for discoloration, lesions, or pest activity.',
          estimatedMinutes: 5,
          subSteps: [
            { id: 'sub4-1', order: 1, text: 'Inspect stem bases for rot or pests' },
            { id: 'sub4-2', order: 2, text: 'Check soil surface for fungus gnats or algae' },
            { id: 'sub4-3', order: 3, text: 'Look for any unusual stem discoloration' },
          ],
        },
        {
          id: 'step5',
          order: 5,
          title: 'Documentation',
          description: 'Record all findings in the IPM log with location and photos.',
          estimatedMinutes: 2,
          subSteps: [
            { id: 'sub5-1', order: 1, text: 'Complete IPM log entry with date, time, inspector' },
            { id: 'sub5-2', order: 2, text: 'Note any issues with exact plant/location' },
            { id: 'sub5-3', order: 3, text: 'Upload photos to cultivation software' },
            { id: 'sub5-4', order: 4, text: 'If issues found: notify Cultivation Manager' },
          ],
        },
      ],
    },
  ],
  '2': [
    {
      id: 'sop2',
      orgId: 'org1',
      title: 'Transplanting Procedure',
      description: 'Safe transplanting protocol to minimize stress and ensure success.',
      category: 'Cultivation',
      version: 1,
      isActive: true,
      createdByUserId: 'u2',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      estimatedTotalMinutes: 45,
      requiredEquipment: [
        'Destination containers (pre-filled)',
        'Growing medium',
        'Rooting hormone (optional)',
        'Spray bottle with water',
        'Clean work surface',
      ],
      safetyNotes: [
        'Handle roots gently to prevent damage',
        'Maintain consistent temperature during transplant',
      ],
      steps: [
        {
          id: 'step1',
          order: 1,
          title: 'Preparation',
          description: 'Prepare workspace and destination containers before handling plants.',
          estimatedMinutes: 10,
          subSteps: [
            { id: 'sub1-1', order: 1, text: 'Fill containers with moistened growing medium' },
            { id: 'sub1-2', order: 2, text: 'Create hole slightly larger than root ball' },
            { id: 'sub1-3', order: 3, text: 'Ensure work area is clean and sanitized' },
          ],
        },
        {
          id: 'step2',
          order: 2,
          title: 'Pre-Watering',
          description: 'Water source plants 2-4 hours before transplanting.',
          estimatedMinutes: 5,
          tipText: 'Moist soil holds together better, protecting roots.',
          subSteps: [
            { id: 'sub2-1', order: 1, text: 'Lightly water all plants to be transplanted' },
            { id: 'sub2-2', order: 2, text: 'Wait 2-4 hours for soil to absorb water' },
          ],
        },
        {
          id: 'step3',
          order: 3,
          title: 'Extract Plant',
          description: 'Gently remove plant while preserving the root ball.',
          warningText: 'Never pull by stem. Always support root ball from below.',
          estimatedMinutes: 15,
          subSteps: [
            { id: 'sub3-1', order: 1, text: 'Invert container supporting stem between fingers' },
            { id: 'sub3-2', order: 2, text: 'Squeeze container sides to release root ball' },
            { id: 'sub3-3', order: 3, text: 'If roots are bound, gently loosen outer roots' },
          ],
        },
        {
          id: 'step4',
          order: 4,
          title: 'Place and Secure',
          description: 'Position plant in new container at the correct depth.',
          estimatedMinutes: 10,
          subSteps: [
            { id: 'sub4-1', order: 1, text: 'Place root ball in prepared hole' },
            { id: 'sub4-2', order: 2, text: 'Ensure plant sits at same depth as before' },
            { id: 'sub4-3', order: 3, text: 'Fill around root ball with growing medium' },
            { id: 'sub4-4', order: 4, text: 'Gently firm soil to remove air pockets' },
          ],
        },
        {
          id: 'step5',
          order: 5,
          title: 'Post-Transplant Care',
          description: 'Water immediately and set up for recovery period.',
          estimatedMinutes: 5,
          subSteps: [
            { id: 'sub5-1', order: 1, text: 'Water thoroughly until runoff appears' },
            { id: 'sub5-2', order: 2, text: 'Reduce light intensity for 24-48 hours' },
            { id: 'sub5-3', order: 3, text: 'Monitor for wilting over next 48 hours' },
            { id: 'sub5-4', order: 4, text: 'Update plant tracking with transplant date' },
          ],
        },
      ],
    },
  ],
  '3': [
    {
      id: 'sop3',
      orgId: 'org1',
      title: 'pH Sensor Calibration',
      description: 'Weekly calibration to ensure accurate pH readings.',
      category: 'Maintenance',
      version: 3,
      isActive: true,
      createdByUserId: 'u2',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      estimatedTotalMinutes: 20,
      requiredEquipment: [
        'pH 4.0 buffer solution',
        'pH 7.0 buffer solution',
        'Distilled water',
        'Clean beakers',
        'Calibration log',
        'Soft cloth',
      ],
      safetyNotes: [
        'Buffer solutions can irritate skin - wear gloves if sensitive',
        'Dispose of used buffer solutions properly',
      ],
      steps: [
        {
          id: 'step1',
          order: 1,
          title: 'Gather Materials',
          description: 'Collect calibration supplies; ensure buffers are at room temperature.',
          estimatedMinutes: 2,
          tipText: 'Buffer solutions should be at same temp as growing environment.',
          subSteps: [
            { id: 'sub1-1', order: 1, text: 'Retrieve pH 4.0 and pH 7.0 buffer solutions' },
            { id: 'sub1-2', order: 2, text: 'Pour small amounts into clean, labeled beakers' },
            { id: 'sub1-3', order: 3, text: 'Have distilled water ready for rinsing' },
          ],
        },
        {
          id: 'step2',
          order: 2,
          title: 'Rinse Probe',
          description: 'Clean the probe to remove residue from previous readings.',
          estimatedMinutes: 2,
          subSteps: [
            { id: 'sub2-1', order: 1, text: 'Rinse probe tip with distilled water' },
            { id: 'sub2-2', order: 2, text: 'Gently blot dry with soft cloth (do not rub)' },
          ],
        },
        {
          id: 'step3',
          order: 3,
          title: 'pH 7.0 Calibration',
          description: 'Calibrate to the neutral reference point first.',
          estimatedMinutes: 5,
          subSteps: [
            { id: 'sub3-1', order: 1, text: 'Immerse probe in pH 7.0 buffer solution' },
            { id: 'sub3-2', order: 2, text: 'Wait for reading to stabilize (30-60 seconds)' },
            { id: 'sub3-3', order: 3, text: 'Enter calibration mode and set to 7.0' },
            { id: 'sub3-4', order: 4, text: 'Confirm calibration was accepted' },
          ],
        },
        {
          id: 'step4',
          order: 4,
          title: 'pH 4.0 Calibration',
          description: 'Calibrate to the acidic reference point.',
          estimatedMinutes: 5,
          subSteps: [
            { id: 'sub4-1', order: 1, text: 'Rinse probe with distilled water' },
            { id: 'sub4-2', order: 2, text: 'Immerse in pH 4.0 buffer solution' },
            { id: 'sub4-3', order: 3, text: 'Wait for reading to stabilize' },
            { id: 'sub4-4', order: 4, text: 'Set calibration to 4.0 and confirm' },
          ],
        },
        {
          id: 'step5',
          order: 5,
          title: 'Verification',
          description: 'Verify calibration accuracy before returning to service.',
          estimatedMinutes: 4,
          warningText: 'If off by more than 0.1, repeat calibration. Persistent issues = replace probe.',
          subSteps: [
            { id: 'sub5-1', order: 1, text: 'Rinse probe and re-test in pH 7.0 buffer' },
            { id: 'sub5-2', order: 2, text: 'Confirm reading is within ±0.1 of 7.0' },
            { id: 'sub5-3', order: 3, text: 'Record results in calibration log' },
            { id: 'sub5-4', order: 4, text: 'Rinse probe and return to service' },
          ],
        },
      ],
    },
  ],
};

export interface TaskComment {
  id: string;
  userId: string;
  userName: string;
  content: string;
  createdAt: string;
}

export const MOCK_COMMENTS: Record<string, TaskComment[]> = {
  '2': [
    {
      id: 'c1',
      userId: 'u2',
      userName: 'Sarah Chen',
      content: 'Roots are looking great on this batch. Ready for transplant.',
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'c2',
      userId: 'u1',
      userName: 'Brandon Burnette',
      content: 'Starting transplant now. Will update when complete.',
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    },
  ],
  '4': [
    {
      id: 'c3',
      userId: 'u3',
      userName: 'Marcus Johnson',
      content: 'Blocked - waiting for IPM treatment to complete before defoliation.',
      createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
};

// Initial SOP progress state (empty - no steps completed)
export const INITIAL_SOP_PROGRESS: Record<string, SopProgress> = {};

