# Tempo Configuration for Harvestry ERP
# Track A: Distributed tracing

server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    zipkin:
      endpoint: 0.0.0.0:9411

ingester:
  max_block_duration: 5m
  max_block_bytes: 1048576

compactor:
  compaction:
    block_retention: 720h  # 30 days

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal
    cache: memcached
    memcached:
      host: memcached:11211
      timeout: 500ms

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: harvestry-dev
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

overrides:
  max_traces_per_user: 100000
  ingestion_rate_limit_bytes: 10000000
  ingestion_burst_size_bytes: 20000000