name: Security - Secrets Scan

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for comprehensive scan

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trufflehog:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@v3.63.0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  detect-secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install detect-secrets
        run: pip install detect-secrets

      - name: Check for committed baseline
        run: |
          if [ ! -f .secrets.baseline ]; then
            echo "❌ .secrets.baseline is missing. Please commit the baseline file to the repository."
            exit 1
          fi

      - name: Scan for secrets
        run: detect-secrets scan --baseline .secrets.baseline --json > report.json

      - name: Check scan results
        run: |
          if jq -e '.results | length > 0' report.json; then
            echo "❌ Secrets detected in the codebase."
            exit 1
          else
            echo "✅ No secrets detected."
          fi

  summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [gitleaks, trufflehog, detect-secrets]
    if: always()
    steps:
      - name: Check all scans
        run: |
          echo "All security scans completed"
          if [ "${{ needs.gitleaks.result }}" != "success" ] || \
             [ "${{ needs.trufflehog.result }}" != "success" ] || \
             [ "${{ needs.detect-secrets.result }}" != "success" ]; then
            echo "⚠️ One or more security scans detected issues"
            exit 1
          fi
          echo "✅ No secrets detected"
