name: Security - Secrets Scan

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for comprehensive scan

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trufflehog:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@v3.63.0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  detect-secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install detect-secrets
        run: pip install detect-secrets

      - name: Check for committed baseline
        run: |
          if [ ! -f .secrets.baseline ]; then
            echo "❌ .secrets.baseline is missing. Please commit the baseline file to the repository."
            exit 1
          fi

      - name: Scan for secrets
        run: detect-secrets scan --baseline .secrets.baseline --json > report.json

      - name: Check scan results against baseline
        run: |
          # Check if the report contains any new findings
          NEW_FINDINGS=$(jq '.results | length' report.json)

          if [ "$NEW_FINDINGS" -eq 0 ]; then
            echo "✅ No new secrets detected beyond baseline."
          else
            echo "❌ New secrets detected that are not in the baseline."
            echo "Found $NEW_FINDINGS new potential secrets."
            echo ""
            echo "New findings:"
            jq -r '.results | keys[] as $filename | .results[$filename][] | "  \($filename):\(.line_number): \(.type) - \(.hashed_secret)"' report.json
            echo ""
            echo "If you intentionally added secrets, please update the baseline by running:"
            echo "detect-secrets scan --baseline .secrets.baseline --update .secrets.baseline"
            exit 1
          fi

  summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [gitleaks, trufflehog, detect-secrets]
    if: always()
    steps:
      - name: Check all scans
        run: |
          echo "All security scans completed"
          if [ "${{ needs.gitleaks.result }}" != "success" ] || \
             [ "${{ needs.trufflehog.result }}" != "success" ] || \
             [ "${{ needs.detect-secrets.result }}" != "success" ]; then
            echo "⚠️ One or more security scans detected issues"
            exit 1
          fi
          echo "✅ No secrets detected"
